# Site settings
title: 
header-img: img/home-bg.png
email: justin-kim1@hotmail.com
copyright_name: justinkim1
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  justinkim1
learn_profile: justinkim1
email_username: justin-kim1@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
